workflow:
    rules:
        - if: $CI_COMMIT_TAG
        - if: $CI_COMMIT_BRANCH
        - if: $CI_MERGE_REQUEST_IID

image:
    name: debian:stable

stages:
    - test

test:
    stage: test
    before_script:
        - apt -y update
        - apt -y install git golang
    script:
        - go test -v
